version: "3.7"
volumes:
  mongo-config:
  mongo-data:
services:
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongo-config
        target: /data/configdb
      - type: volume
        source: mongo-data
        target: /data/db